//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Project/Scripts/InputSystem/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Player_Actions"",
            ""id"": ""125a5eda-6da1-45a1-81ed-2cda78f9891a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4f8f5c79-e560-4851-8bc0-896740872521"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1dcc4412-a305-4053-ae42-55cca0088570"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateView"",
                    ""type"": ""Value"",
                    ""id"": ""07aebe06-bff4-43a9-9c60-109e329f738d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""fb1e7112-b73a-4ec4-a422-53cfb2098e39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""c16805a6-01c8-4fe4-9380-28fb2782f5f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAttack"",
                    ""type"": ""Button"",
                    ""id"": ""c1991abe-9bdb-488d-8eca-418a3c596592"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurtleThrowAndGrab"",
                    ""type"": ""Button"",
                    ""id"": ""b0696756-2a7b-42a2-84fb-33cdc742c6fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastForwardAnimation"",
                    ""type"": ""Button"",
                    ""id"": ""bf8ba3e4-d38d-4c31-80b6-115d2bc6696d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelSkip"",
                    ""type"": ""Button"",
                    ""id"": ""d2d5853a-54a7-454b-8320-1890cc18de70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MagnetPowerUp"",
                    ""type"": ""Button"",
                    ""id"": ""f7fefc36-2a61-4cae-a89d-b12fdbd26154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShieldPowerUp"",
                    ""type"": ""Button"",
                    ""id"": ""dd758dc4-c9fd-4737-9f9e-c59754f38049"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Punch"",
                    ""type"": ""Button"",
                    ""id"": ""c96192c6-3122-4036-807a-6c848f20c5de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Screenshot"",
                    ""type"": ""Button"",
                    ""id"": ""1d3e1c47-f55c-4253-b2b9-5ee1fe4b7d3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""3271b362-2157-4905-a9e7-845bf6453346"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""02c81187-d95e-46ea-8e14-35ae610aaee7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8cba6553-4e02-42e7-8e38-819b6af0e8de"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6d143038-e309-4714-807d-0b335b6f3028"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3f4fe48f-d645-4726-997b-97ea7f0fde49"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff4d5d25-9c44-4191-bdeb-deeb5389f35f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""0c48a675-4363-4f61-aa76-fbaea10d1152"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e9b24971-3587-42b9-becd-175def490062"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48baf664-a518-43d3-9fe1-86e2c2e7b993"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c02a065f-b458-4242-8244-2044fab20e05"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a45e2bc0-1975-4c9e-9474-0244014b62ae"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7460a6cc-926c-4ce9-b5d7-e979e959a278"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27638c80-503b-483b-ae5a-ed8d0b86af11"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""f502f103-7336-431c-82d4-b6dcdf74d169"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3eef28ca-718c-41d8-840f-f12519e3fd95"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""225d6b3b-a4cb-4bc4-8656-7f77c61de5e4"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c6b028de-daca-4a74-96b5-9bf63ff5ff9a"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d35ea6d0-55d0-4049-a67e-8010afd49d63"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad Right"",
                    ""id"": ""e5e407c4-42e6-41fb-8206-03972653e52a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b28c6846-3165-4efa-988f-71cd4043ded4"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ea50a712-930e-470f-8113-b0d446d9df5e"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f4fb1c9-f99a-425f-864e-7a910d7176b7"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f3c0ad9e-89d1-467f-8c24-e938add017b4"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""eb2830ad-cf72-4218-86df-1f51e88886e3"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8252b6c2-f643-4fce-bbe9-6849b1273671"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a7b0ab3-804c-4c39-9d97-6f7dec7ae6a2"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d681ab8-2e6d-4158-b2de-17875902ac3c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9397fd03-128a-4701-aea3-77eb9d69098a"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""PrimaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ab17458-675c-494e-badd-a0a4656fe7f2"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""PrimaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d3f191d-2cec-47ce-ba20-f317e9ece088"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""FastForwardAnimation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21e9545f-b438-4e35-abd1-f0d9bec8a0a4"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcf153ee-0c52-4ce3-819b-19b49f638421"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MagnetPowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5061e0ec-e4b8-48ee-b4a1-01389c1202c1"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""MagnetPowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5a307d4-0c06-4674-9f24-daecd8214d57"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ShieldPowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a9b7f90-6a18-47da-8a54-b0c643d97ab9"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ShieldPowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d93dcde8-8d9c-4035-83d0-b87bbc1da022"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""TurtleThrowAndGrab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dbd98b1-a47b-423f-b06f-2ff4ef7aa8fe"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""TurtleThrowAndGrab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eba44baa-0459-4a7d-9257-2f74e91731aa"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42d12e8b-ea4d-4a45-995f-550e9a299ac4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3673588-3855-4136-afa5-865eadf1519d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""015ad6fc-4833-4e63-9c96-748c16dba991"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XboxController"",
            ""bindingGroup"": ""XboxController"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mouse"",
            ""bindingGroup"": ""Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player_Actions
        m_Player_Actions = asset.FindActionMap("Player_Actions", throwIfNotFound: true);
        m_Player_Actions_Movement = m_Player_Actions.FindAction("Movement", throwIfNotFound: true);
        m_Player_Actions_Jump = m_Player_Actions.FindAction("Jump", throwIfNotFound: true);
        m_Player_Actions_RotateView = m_Player_Actions.FindAction("RotateView", throwIfNotFound: true);
        m_Player_Actions_SwitchCamera = m_Player_Actions.FindAction("SwitchCamera", throwIfNotFound: true);
        m_Player_Actions_Walk = m_Player_Actions.FindAction("Walk", throwIfNotFound: true);
        m_Player_Actions_PrimaryAttack = m_Player_Actions.FindAction("PrimaryAttack", throwIfNotFound: true);
        m_Player_Actions_TurtleThrowAndGrab = m_Player_Actions.FindAction("TurtleThrowAndGrab", throwIfNotFound: true);
        m_Player_Actions_FastForwardAnimation = m_Player_Actions.FindAction("FastForwardAnimation", throwIfNotFound: true);
        m_Player_Actions_LevelSkip = m_Player_Actions.FindAction("LevelSkip", throwIfNotFound: true);
        m_Player_Actions_MagnetPowerUp = m_Player_Actions.FindAction("MagnetPowerUp", throwIfNotFound: true);
        m_Player_Actions_ShieldPowerUp = m_Player_Actions.FindAction("ShieldPowerUp", throwIfNotFound: true);
        m_Player_Actions_Punch = m_Player_Actions.FindAction("Punch", throwIfNotFound: true);
        m_Player_Actions_Screenshot = m_Player_Actions.FindAction("Screenshot", throwIfNotFound: true);
        m_Player_Actions_MouseClick = m_Player_Actions.FindAction("MouseClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Actions
    private readonly InputActionMap m_Player_Actions;
    private IPlayer_ActionsActions m_Player_ActionsActionsCallbackInterface;
    private readonly InputAction m_Player_Actions_Movement;
    private readonly InputAction m_Player_Actions_Jump;
    private readonly InputAction m_Player_Actions_RotateView;
    private readonly InputAction m_Player_Actions_SwitchCamera;
    private readonly InputAction m_Player_Actions_Walk;
    private readonly InputAction m_Player_Actions_PrimaryAttack;
    private readonly InputAction m_Player_Actions_TurtleThrowAndGrab;
    private readonly InputAction m_Player_Actions_FastForwardAnimation;
    private readonly InputAction m_Player_Actions_LevelSkip;
    private readonly InputAction m_Player_Actions_MagnetPowerUp;
    private readonly InputAction m_Player_Actions_ShieldPowerUp;
    private readonly InputAction m_Player_Actions_Punch;
    private readonly InputAction m_Player_Actions_Screenshot;
    private readonly InputAction m_Player_Actions_MouseClick;
    public struct Player_ActionsActions
    {
        private @PlayerActions m_Wrapper;
        public Player_ActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Actions_Movement;
        public InputAction @Jump => m_Wrapper.m_Player_Actions_Jump;
        public InputAction @RotateView => m_Wrapper.m_Player_Actions_RotateView;
        public InputAction @SwitchCamera => m_Wrapper.m_Player_Actions_SwitchCamera;
        public InputAction @Walk => m_Wrapper.m_Player_Actions_Walk;
        public InputAction @PrimaryAttack => m_Wrapper.m_Player_Actions_PrimaryAttack;
        public InputAction @TurtleThrowAndGrab => m_Wrapper.m_Player_Actions_TurtleThrowAndGrab;
        public InputAction @FastForwardAnimation => m_Wrapper.m_Player_Actions_FastForwardAnimation;
        public InputAction @LevelSkip => m_Wrapper.m_Player_Actions_LevelSkip;
        public InputAction @MagnetPowerUp => m_Wrapper.m_Player_Actions_MagnetPowerUp;
        public InputAction @ShieldPowerUp => m_Wrapper.m_Player_Actions_ShieldPowerUp;
        public InputAction @Punch => m_Wrapper.m_Player_Actions_Punch;
        public InputAction @Screenshot => m_Wrapper.m_Player_Actions_Screenshot;
        public InputAction @MouseClick => m_Wrapper.m_Player_Actions_MouseClick;
        public InputActionMap Get() { return m_Wrapper.m_Player_Actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_ActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer_ActionsActions instance)
        {
            if (m_Wrapper.m_Player_ActionsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @RotateView.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRotateView;
                @RotateView.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRotateView;
                @RotateView.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRotateView;
                @SwitchCamera.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnSwitchCamera;
                @Walk.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWalk;
                @PrimaryAttack.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPrimaryAttack;
                @PrimaryAttack.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPrimaryAttack;
                @PrimaryAttack.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPrimaryAttack;
                @TurtleThrowAndGrab.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnTurtleThrowAndGrab;
                @TurtleThrowAndGrab.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnTurtleThrowAndGrab;
                @TurtleThrowAndGrab.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnTurtleThrowAndGrab;
                @FastForwardAnimation.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFastForwardAnimation;
                @FastForwardAnimation.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFastForwardAnimation;
                @FastForwardAnimation.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFastForwardAnimation;
                @LevelSkip.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLevelSkip;
                @LevelSkip.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLevelSkip;
                @LevelSkip.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLevelSkip;
                @MagnetPowerUp.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMagnetPowerUp;
                @MagnetPowerUp.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMagnetPowerUp;
                @MagnetPowerUp.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMagnetPowerUp;
                @ShieldPowerUp.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnShieldPowerUp;
                @ShieldPowerUp.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnShieldPowerUp;
                @ShieldPowerUp.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnShieldPowerUp;
                @Punch.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPunch;
                @Punch.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPunch;
                @Punch.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnPunch;
                @Screenshot.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnScreenshot;
                @Screenshot.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnScreenshot;
                @Screenshot.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnScreenshot;
                @MouseClick.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMouseClick;
                @MouseClick.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMouseClick;
                @MouseClick.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMouseClick;
            }
            m_Wrapper.m_Player_ActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @RotateView.started += instance.OnRotateView;
                @RotateView.performed += instance.OnRotateView;
                @RotateView.canceled += instance.OnRotateView;
                @SwitchCamera.started += instance.OnSwitchCamera;
                @SwitchCamera.performed += instance.OnSwitchCamera;
                @SwitchCamera.canceled += instance.OnSwitchCamera;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @PrimaryAttack.started += instance.OnPrimaryAttack;
                @PrimaryAttack.performed += instance.OnPrimaryAttack;
                @PrimaryAttack.canceled += instance.OnPrimaryAttack;
                @TurtleThrowAndGrab.started += instance.OnTurtleThrowAndGrab;
                @TurtleThrowAndGrab.performed += instance.OnTurtleThrowAndGrab;
                @TurtleThrowAndGrab.canceled += instance.OnTurtleThrowAndGrab;
                @FastForwardAnimation.started += instance.OnFastForwardAnimation;
                @FastForwardAnimation.performed += instance.OnFastForwardAnimation;
                @FastForwardAnimation.canceled += instance.OnFastForwardAnimation;
                @LevelSkip.started += instance.OnLevelSkip;
                @LevelSkip.performed += instance.OnLevelSkip;
                @LevelSkip.canceled += instance.OnLevelSkip;
                @MagnetPowerUp.started += instance.OnMagnetPowerUp;
                @MagnetPowerUp.performed += instance.OnMagnetPowerUp;
                @MagnetPowerUp.canceled += instance.OnMagnetPowerUp;
                @ShieldPowerUp.started += instance.OnShieldPowerUp;
                @ShieldPowerUp.performed += instance.OnShieldPowerUp;
                @ShieldPowerUp.canceled += instance.OnShieldPowerUp;
                @Punch.started += instance.OnPunch;
                @Punch.performed += instance.OnPunch;
                @Punch.canceled += instance.OnPunch;
                @Screenshot.started += instance.OnScreenshot;
                @Screenshot.performed += instance.OnScreenshot;
                @Screenshot.canceled += instance.OnScreenshot;
                @MouseClick.started += instance.OnMouseClick;
                @MouseClick.performed += instance.OnMouseClick;
                @MouseClick.canceled += instance.OnMouseClick;
            }
        }
    }
    public Player_ActionsActions @Player_Actions => new Player_ActionsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("XboxController");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    private int m_MouseSchemeIndex = -1;
    public InputControlScheme MouseScheme
    {
        get
        {
            if (m_MouseSchemeIndex == -1) m_MouseSchemeIndex = asset.FindControlSchemeIndex("Mouse");
            return asset.controlSchemes[m_MouseSchemeIndex];
        }
    }
    public interface IPlayer_ActionsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRotateView(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnPrimaryAttack(InputAction.CallbackContext context);
        void OnTurtleThrowAndGrab(InputAction.CallbackContext context);
        void OnFastForwardAnimation(InputAction.CallbackContext context);
        void OnLevelSkip(InputAction.CallbackContext context);
        void OnMagnetPowerUp(InputAction.CallbackContext context);
        void OnShieldPowerUp(InputAction.CallbackContext context);
        void OnPunch(InputAction.CallbackContext context);
        void OnScreenshot(InputAction.CallbackContext context);
        void OnMouseClick(InputAction.CallbackContext context);
    }
}
